# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-24 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190424_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='id',
            new_name='blogid',
        ),
    ]
