# Generated by Django 2.2 on 2020-04-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200419_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='clans',
            name='roomid',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
